-- Insert Ukrainian dubbed movies into the database
INSERT INTO movies (tmdb_id, title, title_en, description, rating, year, duration, genres, poster_url, backdrop_url, director, cast_members, has_voiceover)
VALUES
  (530915, 'Захар Беркут', 'Zakhar Berkut', 'Епічна боротьба карпатських горян проти монгольської навали. Героїчна оборона, стійкість та братерство в найважчі часи.', 8.2, 2019, '120 хв', '{"Історичний","Драма","Бойовик"}', 'https://image.tmdb.org/t/p/w342/mScnfbZvUvBRDt9lmGmZvBmJ26.jpg', 'https://image.tmdb.org/t/p/w1280/aSy3P3ZFfGIQfXhNCPDZH4WIvKb.jpg', 'Ахтем Сеітаблаєв', '{"Микола Лупій","Богдан Коваль"}', true),
  (465136, 'Кіборги', 'Cyborgs', 'Героїчна оборона Донецького аеропорту. Мужність та братерство військових, які не здалися ворогові.', 8.5, 2017, '112 хв', '{"Бойовик","Військовий","Драма"}', 'https://image.tmdb.org/t/p/w342/qNQxP9LCzGOL6BrJzFEALDVPHvN.jpg', 'https://image.tmdb.org/t/p/w1280/fIx8NqiKdUBdJKhwZHIXQmNjUKx.jpg', 'Ахтем Сеітаблаєв', '{"Гліб Кокорін","Олег Волошин"}', true),
  (610201, 'Атлантида', 'Atlantis', 'Постапокаліптична драма про ветерана у зруйнованому Донбасі. Пошук смислу та міцних людських зв\'язків у часи катастрофи.', 7.8, 2020, '106 хв', '{"Драма","Sci-Fi","Військовий"}', 'https://image.tmdb.org/t/p/w342/h0E4Q9YBVL3VgPvZ5rh8QqJ5p5K.jpg', 'https://image.tmdb.org/t/p/w1280/y5Z8Ax7NdvI7dGNjDqmZnRvX0hF.jpg', 'Валентин Васянович', '{"Квітка Евджен"}', true),
  (467531, 'Ціна правди', 'Mr. Jones', 'Журналіст розкриває правду про Голодомор в Україні. Грізна історія про боротьбу зі свідомістю та брехнею.', 8.1, 2019, '119 хв', '{"Історичний","Драма","Біографія"}', 'https://image.tmdb.org/t/p/w342/l7OL8g1DvYmALV3pBFZhP7yN7Xz.jpg', 'https://image.tmdb.org/t/p/w1280/jCw4TAhvVQEjFiVV6xLVPqh6FJl.jpg', 'Агнєшка Холланд', '{"Джеймс Нортон","Ванесса Кірбі"}', true),
  (746969, 'Стоп-Земля', 'Stop-Earth', 'Фантастична драма про дівчину, яка може зупиняти час. Розмірковування про вибір, наслідки та цінність кожної секунди.', 7.8, 2020, '105 хв', '{"Sci-Fi","Драма"}', 'https://image.tmdb.org/t/p/w342/mI2ePo9jLqWcyy4k4HZx8xaMJ3Z.jpg', 'https://image.tmdb.org/t/p/w1280/3Z6pTW2t4dB1i3qVPcT7zV5qAIm.jpg', 'Катерина Горностай', '{"Владислав Отеленюк"}', true),
  (572154, 'Додому', 'Home', 'Зворушлива драма про повернення. Родинні зв\'язки, пробачення та надія на нові початки.', 7.9, 2019, '110 хв', '{"Драма"}', 'https://image.tmdb.org/t/p/w342/3ewNhv0o7FDq71OhlQlgNzY2cFe.jpg', 'https://image.tmdb.org/t/p/w1280/hSmjlNwMBa8QlmJqJHQv8VoUSN9.jpg', 'Наріман Алієв', '{"Домініка Ланді","Богдан Коваль"}', true),
  (857041, 'Бліндаж', 'Blindage', 'Люди у прифронтовій зоні — їхня стійкість та надія на майбутнє. Інтимна розповідь про сьогодення війни.', 8.0, 2021, '92 хв', '{"Драма","Військовий"}', 'https://image.tmdb.org/t/p/w342/2YKdvvbJMiLvZsj7LfYyQcR1zWj.jpg', 'https://image.tmdb.org/t/p/w1280/7P9TpNvVVKLQtqzKKrBRhZv9nJf.jpg', 'Олександр Течинський', '{"Павло Табаков","Алла Вовк"}', true),
  (737173, 'Толока', 'Toloka', 'Містична історія: реальність переплітається з українським фольклором. Атмосфера, напруга та дивні явища.', 7.5, 2020, '95 хв', '{"Трилер","Містика","Драма"}', 'https://image.tmdb.org/t/p/w342/wUjEpfLIy6LvO1Z6FKq9V5PTQUM.jpg', 'https://image.tmdb.org/t/p/w1280/vMnF2cVLXSw3yJ0t9F4tnD2bnKI.jpg', 'Михайло Іллєнко', '{"Юлія Кравченко","Кирилл Киселёв"}', true),
  (192210, 'Поводир', 'The Guide', 'Американець в Україні 30-х під час Голодомору. Трагедія та стійкість людського духу.', 7.6, 2014, '99 хв', '{"Історичний","Драма"}', 'https://image.tmdb.org/t/p/w342/k0bvYOSqnN8rGEBf3UqxVIoYzBE.jpg', 'https://image.tmdb.org/t/p/w1280/wX3H5Mbs2UKnhP1F9EW4zYs6h2l.jpg', 'Олесь Санін', '{"М\'єллі Мела"}', true),
  (619592, 'Чорний ворон', 'Black Raven', 'Атмосфірний трилер — таємниці карпатських лісів та древні легенди. Загубленість та страх у невідомому.', 7.3, 2019, '87 хв', '{"Трилер","Містика"}', 'https://image.tmdb.org/t/p/w342/7G0j9BhRnEGrE2m4jYQmFr2J5g0.jpg', 'https://image.tmdb.org/t/p/w1280/7CnCG8G5R6G5I3HJL9Kn8b8N9k0.jpg', 'Тарас Химич', '{"Юлія Волкова"}', true),
  (11216, 'The Dark Knight Rises', 'The Dark Knight Rises', 'Чорний лицар повертається — для останнього поєдинку. Епічний завершення трилогії.', 8.5, 2012, '164 хв', '{"Бойовик","Драма","Трилер"}', 'https://image.tmdb.org/t/p/w342/fWAKWC9sJ0dT0nnN8ghWRR6M7qb.jpg', 'https://image.tmdb.org/t/p/w1280/l7OL8g1DvYmALV3pBFZhP7yN7Xz.jpg', 'Крістофер Нолан', '{"Крістіан Бейл","Майкл Кейн"}', true),
  (550, 'Fight Club', 'Fight Club', 'Розповідь про підпільний клуб та змініння світобачення. Шедевр психологічного трилера.', 8.8, 1999, '139 хв', '{"Драма","Трилер"}', 'https://image.tmdb.org/t/p/w342/fWAKWC9sJ0dT0nnN8ghWRR6M7qb.jpg', 'https://image.tmdb.org/t/p/w1280/l7OL8g1DvYmALV3pBFZhP7yN7Xz.jpg', 'Девід Фінчер', '{"Бред Піт","Едвард Нортон"}', true),
  (278, 'The Shawshank Redemption', 'The Shawshank Redemption', 'Історія надії та дружби в стінах в\'язниці. Один з найкращих фільмів всіх часів.', 9.3, 1994, '142 хв', '{"Драма"}', 'https://image.tmdb.org/t/p/w342/fWAKWC9sJ0dT0nnN8ghWRR6M7qb.jpg', 'https://image.tmdb.org/t/p/w1280/l7OL8g1DvYmALV3pBFZhP7yN7Xz.jpg', 'Френк Дарабонт', '{"Тім Роббінс","Морган Фрімен"}', true),
  (807, 'Se7en', 'Se7en', 'Темний серійний трилер про двох детективів та недель жахів. Шедевр гріму та напруги.', 8.6, 1995, '127 хв', '{"Трилер","Кримінал","Драма"}', 'https://image.tmdb.org/t/p/w342/fWAKWC9sJ0dT0nnN8ghWRR6M7qb.jpg', 'https://image.tmdb.org/t/p/w1280/l7OL8g1DvYmALV3pBFZhP7yN7Xz.jpg', 'Девід Фінчер', '{"Бред Піт","Морган Фрімен"}', true),
  (120, 'The Lord of the Rings: The Fellowship of the Ring', 'The Lord of the Rings: The Fellowship of the Ring', 'Епічна фентезійна сага про намагання знищити кільце влади. Грандіозне кіно.', 8.9, 2001, '178 хв', '{"Фентезі","Пригоди","Драма"}', 'https://image.tmdb.org/t/p/w342/fWAKWC9sJ0dT0nnN8ghWRR6M7qb.jpg', 'https://image.tmdb.org/t/p/w1280/l7OL8g1DvYmALV3pBFZhP7yN7Xz.jpg', 'Пітер Джексон', '{"Іан МакКеллен","Ілія Вуд"}', true);

-- Insert Ukrainian dubbing information
INSERT INTO dubbing (tmdb_id, title_uk, studio, quality, has_subtitles, voice_actors, source_site, release_date)
VALUES
  (530915, 'Захар Беркут', '1+1 Кіно', '1080p', true, 'Сергій Паламарчук, Руслан Кучер', 'kinokrad.co', NOW()),
  (465136, 'Кіборги', 'Канал 1+1', 'Full HD', true, 'Гліб Кокорін, Олег Волошин', 'kinokrad.co', NOW()),
  (610201, 'Атлантида', 'Перший Український', 'Full HD', true, 'Квітка Евджен', 'kinokrad.co', NOW()),
  (467531, 'Ціна правди', 'Канал 1+1', 'Full HD', true, 'Вахтанг Панікашвілі', 'kinokrad.co', NOW()),
  (746969, 'Стоп-Земля', 'Дім Кіно', 'HD', false, 'Владислав Отеленюк', 'kinokrad.co', NOW()),
  (572154, 'Додому', '1+1 Кіно', '1080p', true, 'Богдан Коваль, Домініка Ланді', 'kinokrad.co', NOW()),
  (857041, 'Бліндаж', 'Перший Український', 'Full HD', true, 'Павло Табаков, Алла Вовк', 'kinokrad.co', NOW()),
  (737173, 'Толока', 'Канал 1+1', 'HD', true, 'Юлія Кравченко', 'kinokrad.co', NOW()),
  (192210, 'Поводир', 'Дім Кіно', 'HD', true, 'М\'єллі Мела', 'kinokrad.co', NOW()),
  (619592, 'Чорний ворон', '1+1 Кіно', '1080p', false, 'Юлія Волкова', 'kinokrad.co', NOW()),
  (11216, 'Темний лицар встає', 'Канал 1+1', 'Full HD', true, 'Сергій Паламарчук', 'kinokrad.co', NOW()),
  (550, 'Клуб Бійців', '1+1 Кіно', 'Full HD', false, 'Василь Лановий', 'kinokrad.co', NOW()),
  (278, 'Гра без правил', 'Дім Кіно', 'Full HD', true, 'Сергій Паламарчук', 'kinokrad.co', NOW()),
  (807, 'Семеро', 'Канал 1+1', 'HD', false, 'Руслан Кучер', 'kinokrad.co', NOW()),
  (120, 'Володар Кілець: Братство Кільця', '1+1 Кіно', '1080p', true, 'Сергій Паламарчук, Васіл Лановой', 'kinokrad.co', NOW());
